class Country {
  final String name;
  final String countryCode;

  Country({required this.name, required this.countryCode});
}

class CountryHelper {
  static final List<Country> countries = [
    Country(name: 'Afghanistan', countryCode: 'AF'),
    Country(name: 'Åland Islands', countryCode: 'AX'),
    Country(name: 'Albania', countryCode: 'AL'),
    Country(name: 'Algeria', countryCode: 'DZ'),
    Country(name: 'American Samoa', countryCode: 'AS'),
    Country(name: 'Andorra', countryCode: 'AD'),
    Country(name: 'Angola', countryCode: 'AO'),
    Country(name: 'Anguilla', countryCode: 'AI'),
    Country(name: 'Antarctica', countryCode: 'AQ'),
    Country(name: 'Antigua and Barbuda', countryCode: 'AG'),
    Country(name: 'Argentina', countryCode: 'AR'),
    Country(name: 'Armenia', countryCode: 'AM'),
    Country(name: 'Aruba', countryCode: 'AW'),
    Country(name: 'Australia', countryCode: 'AU'),
    Country(name: 'Austria', countryCode: 'AT'),
    Country(name: 'Azerbaijan', countryCode: 'AZ'),
    Country(name: 'Bahamas', countryCode: 'BS'),
    Country(name: 'Bahrain', countryCode: 'BH'),
    Country(name: 'Bangladesh', countryCode: 'BD'),
    Country(name: 'Barbados', countryCode: 'BB'),
    Country(name: 'Belarus', countryCode: 'BY'),
    Country(name: 'Belgium', countryCode: 'BE'),
    Country(name: 'Belize', countryCode: 'BZ'),
    Country(name: 'Benin', countryCode: 'BJ'),
    Country(name: 'Bermuda', countryCode: 'BM'),
    Country(name: 'Bhutan', countryCode: 'BT'),
    Country(name: 'Bolivia', countryCode: 'BO'),
    Country(name: 'Bonaire, Sint Eustatius and Saba', countryCode: 'BQ'),
    Country(name: 'Bosnia and Herzegovina', countryCode: 'BA'),
    Country(name: 'Botswana', countryCode: 'BW'),
    Country(name: 'Bouvet Island', countryCode: 'BV'),
    Country(name: 'Brazil', countryCode: 'BR'),
    Country(name: 'British Indian Ocean Territory', countryCode: 'IO'),
    Country(name: 'Brunei Darussalam', countryCode: 'BN'),
    Country(name: 'Bulgaria', countryCode: 'BG'),
    Country(name: 'Burkina Faso', countryCode: 'BF'),
    Country(name: 'Burundi', countryCode: 'BI'),
    Country(name: 'Cabo Verde', countryCode: 'CV'),
    Country(name: 'Cambodia', countryCode: 'KH'),
    Country(name: 'Cameroon', countryCode: 'CM'),
    Country(name: 'Canada', countryCode: 'CA'),
    Country(name: 'Cayman Islands', countryCode: 'KY'),
    Country(name: 'Central African Republic', countryCode: 'CF'),
    Country(name: 'Chad', countryCode: 'TD'),
    Country(name: 'Chile', countryCode: 'CL'),
    Country(name: 'China', countryCode: 'CN'),
    Country(name: 'Christmas Island', countryCode: 'CX'),
    Country(name: 'Cocos (Keeling) Islands', countryCode: 'CC'),
    Country(name: 'Colombia', countryCode: 'CO'),
    Country(name: 'Comoros', countryCode: 'KM'),
    Country(name: 'Congo', countryCode: 'CG'),
    Country(name: 'Congo, Democratic Republic of the', countryCode: 'CD'),
    Country(name: 'Cook Islands', countryCode: 'CK'),
    Country(name: 'Costa Rica', countryCode: 'CR'),
    Country(name: "Côte d'Ivoire", countryCode: 'CI'),
    Country(name: 'Croatia', countryCode: 'HR'),
    Country(name: 'Cuba', countryCode: 'CU'),
    Country(name: 'Curaçao', countryCode: 'CW'),
    Country(name: 'Cyprus', countryCode: 'CY'),
    Country(name: 'Czech Republic', countryCode: 'CZ'),
    Country(name: 'Denmark', countryCode: 'DK'),
    Country(name: 'Djibouti', countryCode: 'DJ'),
    Country(name: 'Dominica', countryCode: 'DM'),
    Country(name: 'Dominican Republic', countryCode: 'DO'),
    Country(name: 'Ecuador', countryCode: 'EC'),
    Country(name: 'Egypt', countryCode: 'EG'),
    Country(name: 'El Salvador', countryCode: 'SV'),
    Country(name: 'Equatorial Guinea', countryCode: 'GQ'),
    Country(name: 'Eritrea', countryCode: 'ER'),
    Country(name: 'Estonia', countryCode: 'EE'),
    Country(name: 'Eswatini', countryCode: 'SZ'),
    Country(name: 'Ethiopia', countryCode: 'ET'),
    Country(name: 'Falkland Islands', countryCode: 'FK'),
    Country(name: 'Faroe Islands', countryCode: 'FO'),
    Country(name: 'Fiji', countryCode: 'FJ'),
    Country(name: 'Finland', countryCode: 'FI'),
    Country(name: 'France', countryCode: 'FR'),
    Country(name: 'French Guiana', countryCode: 'GF'),
    Country(name: 'French Polynesia', countryCode: 'PF'),
    Country(name: 'French Southern Territories', countryCode: 'TF'),
    Country(name: 'Gabon', countryCode: 'GA'),
    Country(name: 'Gambia', countryCode: 'GM'),
    Country(name: 'Georgia', countryCode: 'GE'),
    Country(name: 'Germany', countryCode: 'DE'),
    Country(name: 'Ghana', countryCode: 'GH'),
    Country(name: 'Gibraltar', countryCode: 'GI'),
    Country(name: 'Greece', countryCode: 'GR'),
    Country(name: 'Greenland', countryCode: 'GL'),
    Country(name: 'Grenada', countryCode: 'GD'),
    Country(name: 'Guadeloupe', countryCode: 'GP'),
    Country(name: 'Guam', countryCode: 'GU'),
    Country(name: 'Guatemala', countryCode: 'GT'),
    Country(name: 'Guernsey', countryCode: 'GG'),
    Country(name: 'Guinea', countryCode: 'GN'),
    Country(name: 'Guinea-Bissau', countryCode: 'GW'),
    Country(name: 'Guyana', countryCode: 'GY'),
    Country(name: 'Haiti', countryCode: 'HT'),
    Country(name: 'Heard Island and McDonald Islands', countryCode: 'HM'),
    Country(name: 'Holy See', countryCode: 'VA'),
    Country(name: 'Honduras', countryCode: 'HN'),
    Country(name: 'Hong Kong', countryCode: 'HK'),
    Country(name: 'Hungary', countryCode: 'HU'),
    Country(name: 'Iceland', countryCode: 'IS'),
    Country(name: 'India', countryCode: 'IN'),
    Country(name: 'Indonesia', countryCode: 'ID'),
    Country(name: 'Iran', countryCode: 'IR'),
    Country(name: 'Iraq', countryCode: 'IQ'),
    Country(name: 'Ireland', countryCode: 'IE'),
    Country(name: 'Isle of Man', countryCode: 'IM'),
    Country(name: 'Israel', countryCode: 'IL'),
    Country(name: 'Italy', countryCode: 'IT'),
    Country(name: 'Jamaica', countryCode: 'JM'),
    Country(name: 'Japan', countryCode: 'JP'),
    Country(name: 'Jersey', countryCode: 'JE'),
    Country(name: 'Jordan', countryCode: 'JO'),
    Country(name: 'Kazakhstan', countryCode: 'KZ'),
    Country(name: 'Kenya', countryCode: 'KE'),
    Country(name: 'Kiribati', countryCode: 'KI'),
    Country(name: "Korea, Democratic People's Republic of", countryCode: 'KP'),
    Country(name: 'Korea, Republic of', countryCode: 'KR'),
    Country(name: 'Kuwait', countryCode: 'KW'),
    Country(name: 'Kyrgyzstan', countryCode: 'KG'),
    Country(name: "Lao People's Democratic Republic", countryCode: 'LA'),
    Country(name: 'Latvia', countryCode: 'LV'),
    Country(name: 'Lebanon', countryCode: 'LB'),
    Country(name: 'Lesotho', countryCode: 'LS'),
    Country(name: 'Liberia', countryCode: 'LR'),
    Country(name: 'Libya', countryCode: 'LY'),
    Country(name: 'Liechtenstein', countryCode: 'LI'),
    Country(name: 'Lithuania', countryCode: 'LT'),
    Country(name: 'Luxembourg', countryCode: 'LU'),
    Country(name: 'Macao', countryCode: 'MO'),
    Country(name: 'Madagascar', countryCode: 'MG'),
    Country(name: 'Malawi', countryCode: 'MW'),
    Country(name: 'Malaysia', countryCode: 'MY'),
    Country(name: 'Maldives', countryCode: 'MV'),
    Country(name: 'Mali', countryCode: 'ML'),
    Country(name: 'Malta', countryCode: 'MT'),
    Country(name: 'Marshall Islands', countryCode: 'MH'),
    Country(name: 'Martinique', countryCode: 'MQ'),
    Country(name: 'Mauritania', countryCode: 'MR'),
    Country(name: 'Mauritius', countryCode: 'MU'),
    Country(name: 'Mayotte', countryCode: 'YT'),
    Country(name: 'Mexico', countryCode: 'MX'),
    Country(name: 'Micronesia, Federated States of', countryCode: 'FM'),
    Country(name: 'Moldova', countryCode: 'MD'),
    Country(name: 'Monaco', countryCode: 'MC'),
    Country(name: 'Mongolia', countryCode: 'MN'),
    Country(name: 'Montenegro', countryCode: 'ME'),
    Country(name: 'Montserrat', countryCode: 'MS'),
    Country(name: 'Morocco', countryCode: 'MA'),
    Country(name: 'Mozambique', countryCode: 'MZ'),
    Country(name: 'Myanmar', countryCode: 'MM'),
    Country(name: 'Namibia', countryCode: 'NA'),
    Country(name: 'Nauru', countryCode: 'NR'),
    Country(name: 'Nepal', countryCode: 'NP'),
    Country(name: 'Netherlands', countryCode: 'NL'),
    Country(name: 'New Caledonia', countryCode: 'NC'),
    Country(name: 'New Zealand', countryCode: 'NZ'),
    Country(name: 'Nicaragua', countryCode: 'NI'),
    Country(name: 'Niger', countryCode: 'NE'),
    Country(name: 'Nigeria', countryCode: 'NG'),
    Country(name: 'Niue', countryCode: 'NU'),
    Country(name: 'Norfolk Island', countryCode: 'NF'),
    Country(name: 'North Macedonia', countryCode: 'MK'),
    Country(name: 'Northern Mariana Islands', countryCode: 'MP'),
    Country(name: 'Norway', countryCode: 'NO'),
    Country(name: 'Oman', countryCode: 'OM'),
    Country(name: 'Pakistan', countryCode: 'PK'),
    Country(name: 'Palau', countryCode: 'PW'),
    Country(name: 'Palestine, State of', countryCode: 'PS'),
    Country(name: 'Panama', countryCode: 'PA'),
    Country(name: 'Papua New Guinea', countryCode: 'PG'),
    Country(name: 'Paraguay', countryCode: 'PY'),
    Country(name: 'Peru', countryCode: 'PE'),
    Country(name: 'Philippines', countryCode: 'PH'),
    Country(name: 'Pitcairn', countryCode: 'PN'),
    Country(name: 'Poland', countryCode: 'PL'),
    Country(name: 'Portugal', countryCode: 'PT'),
    Country(name: 'Puerto Rico', countryCode: 'PR'),
    Country(name: 'Qatar', countryCode: 'QA'),
    Country(name: 'Réunion', countryCode: 'RE'),
    Country(name: 'Romania', countryCode: 'RO'),
    Country(name: 'Russian Federation', countryCode: 'RU'),
    Country(name: 'Rwanda', countryCode: 'RW'),
    Country(name: 'Saint Barthélemy', countryCode: 'BL'),
    Country(
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        countryCode: 'SH'),
    Country(name: 'Saint Kitts and Nevis', countryCode: 'KN'),
    Country(name: 'Saint Lucia', countryCode: 'LC'),
    Country(name: 'Saint Martin (French part)', countryCode: 'MF'),
    Country(name: 'Saint Pierre and Miquelon', countryCode: 'PM'),
    Country(name: 'Saint Vincent and the Grenadines', countryCode: 'VC'),
    Country(name: 'Samoa', countryCode: 'WS'),
    Country(name: 'San Marino', countryCode: 'SM'),
    Country(name: 'Sao Tome and Principe', countryCode: 'ST'),
    Country(name: 'Saudi Arabia', countryCode: 'SA'),
    Country(name: 'Senegal', countryCode: 'SN'),
    Country(name: 'Serbia', countryCode: 'RS'),
    Country(name: 'Seychelles', countryCode: 'SC'),
    Country(name: 'Sierra Leone', countryCode: 'SL'),
    Country(name: 'Singapore', countryCode: 'SG'),
    Country(name: 'Sint Maarten (Dutch part)', countryCode: 'SX'),
    Country(name: 'Slovakia', countryCode: 'SK'),
    Country(name: 'Slovenia', countryCode: 'SI'),
    Country(name: 'Solomon Islands', countryCode: 'SB'),
    Country(name: 'Somalia', countryCode: 'SO'),
    Country(name: 'South Africa', countryCode: 'ZA'),
    Country(
        name: 'South Georgia and the South Sandwich Islands',
        countryCode: 'GS'),
    Country(name: 'South Sudan', countryCode: 'SS'),
    Country(name: 'Spain', countryCode: 'ES'),
    Country(name: 'Sri Lanka', countryCode: 'LK'),
    Country(name: 'Sudan', countryCode: 'SD'),
    Country(name: 'Suriname', countryCode: 'SR'),
    Country(name: 'Svalbard and Jan Mayen', countryCode: 'SJ'),
    Country(name: 'Sweden', countryCode: 'SE'),
    Country(name: 'Switzerland', countryCode: 'CH'),
    Country(name: 'Syrian Arab Republic', countryCode: 'SY'),
    Country(name: 'Taiwan', countryCode: 'TW'),
    Country(name: 'Tajikistan', countryCode: 'TJ'),
    Country(name: 'Tanzania', countryCode: 'TZ'),
    Country(name: 'Thailand', countryCode: 'TH'),
    Country(name: 'Timor-Leste', countryCode: 'TL'),
    Country(name: 'Togo', countryCode: 'TG'),
    Country(name: 'Tokelau', countryCode: 'TK'),
    Country(name: 'Tonga', countryCode: 'TO'),
    Country(name: 'Trinidad and Tobago', countryCode: 'TT'),
    Country(name: 'Tunisia', countryCode: 'TN'),
    Country(name: 'Turkey', countryCode: 'TR'),
    Country(name: 'Turkmenistan', countryCode: 'TM'),
    Country(name: 'Turks and Caicos Islands', countryCode: 'TC'),
    Country(name: 'Tuvalu', countryCode: 'TV'),
    Country(name: 'Uganda', countryCode: 'UG'),
    Country(name: 'Ukraine', countryCode: 'UA'),
    Country(name: 'United Arab Emirates', countryCode: 'AE'),
    Country(name: 'United Kingdom', countryCode: 'GB'),
    Country(name: 'United States', countryCode: 'US'),
    Country(name: 'United States Minor Outlying Islands', countryCode: 'UM'),
    Country(name: 'Uruguay', countryCode: 'UY'),
    Country(name: 'Uzbekistan', countryCode: 'UZ'),
    Country(name: 'Vanuatu', countryCode: 'VU'),
    Country(name: 'Venezuela', countryCode: 'VE'),
    Country(name: 'Viet Nam', countryCode: 'VN'),
    Country(name: 'Virgin Islands, British', countryCode: 'VG'),
    Country(name: 'Virgin Islands, U.S.', countryCode: 'VI'),
    Country(name: 'Wallis and Futuna', countryCode: 'WF'),
    Country(name: 'Western Sahara', countryCode: 'EH'),
    Country(name: 'Yemen', countryCode: 'YE'),
    Country(name: 'Zambia', countryCode: 'ZM'),
    Country(name: 'Zimbabwe', countryCode: 'ZW')
  ];
}
